aboutme/urls.py
from django.conf.urls import url
from .views import index, message_post, message_table

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_message', message_post, name='add_message'),
	url(r'^result_table', message_table, name='result_table'),
]

aboutus/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
]

dashboard/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
]

praktikum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import dashboard.urls as dashboard
import aboutus.urls as aboutus
#import post.urls as post
import aboutme.urls as aboutme
from django.views.generic import RedirectView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^dashboard/', include(dashboard, namespace='dashboard')),
    url(r'^aboutus/', include(aboutus, namespace='aboutus')),
    #url(r'^post/', include(post, namespace='post')),
    url(r'^aboutme/', include(aboutme, namespace='aboutme')),

    url(r'^$', RedirectView.as_view(url= '/dashboard/', permanent='true'), name='redirect_landing_page')
]

aboutme/models.py
from django.db import models
from datetime import date
from django.utils import timezone

DATE_INPUT_FORMATS = ('%d-%m-%Y')


# Create your models here.


class Person(models.Model):
    name = models.CharField(max_length=30)
    birthdate = models.DateField(default=date.today)
    gender = models.CharField(max_length=6)
    description = models.CharField(max_length=100)
    email = models.EmailField()

class Expertise(models.Model):
    expertise = models.CharField(max_length=255)

class PhotoURL(models.Model):
    model_pic = models.CharField(max_length=255)

# Create your models here.
class Message(models.Model):
    def convertTimezone():
        return timezone.now() + timezone.timedelta(hours=7)


    name = models.CharField(max_length=27)
    email = models.EmailField()
    message = models.TextField()
    created_date = models.DateTimeField(default=convertTimezone)

    def __str__(self):
        return self.message

aboutus/models.py
from django.db import models

# Create your models here.

dashboard/models.py
from django.db import models

# Create your models here.

post/models.py
from django.db import models

# Create your models here.

aboutme/forms.py
from django import forms

class Message_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
        'invalid': 'Isi input dengan email',
    }
    attrs = {
        'class': 'form-control'
    }

    name = forms.CharField(label='Nama', required=False, max_length=27, empty_value='Anonymous', widget=forms.TextInput(attrs=attrs))
    email = forms.EmailField(required=False, widget=forms.EmailInput(attrs=attrs))
    message = forms.CharField(widget=forms.Textarea(attrs=attrs), required=True)

aboutme/views.py
from django.shortcuts import render
from .models import Person, Expertise, PhotoURL, Message
from .forms import Message_Form

# Create your views here.


response = {} 
def index(request):
    html = 'aboutme/aboutme.html'
    person = Person.objects.create(name="Kezia Irene", birthdate="1998-10-15", gender="Female", description="A person who always tries to be a better one", email="irenekezia98@.com")
    expertise = Expertise.objects.create(expertise ="Java and Python")
    expertise = Expertise.objects.create(expertise ="Making Fun Music")
    expertise = Expertise.objects.create(expertise ="Business IT Plan")
    model_pic = expertise = PhotoURL.objects.create(model_pic ="https://0.academia-photos.com/22671060/6165818/6987836/s200_kezia_irene.tesiman.jpg_oh_6c416e6db6c808e5087a71965d1a881a_oe_54ffe395___gda___1426160583_a83ba5be6321a5da3e15978004b85cb7")

    
    response['author']= "Kezia Irene"
    response['name'] = Person.objects.all()[0].name
    response['birthdate'] = Person.objects.all()[0].birthdate
    response['gender'] = Person.objects.all()[0].gender
    response['expertise'] = Expertise.objects.all()[0:3]
    response['description'] = Person.objects.all()[0].description
    response['email'] = Person.objects.all()[0].email
    response['model_pic'] = PhotoURL.objects.all()[0].model_pic

    response['message_form'] = Message_Form
    return render(request, html, response)

def message_post(request):
    form = Message_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['name'] = request.POST['name'] if request.POST['name'] != "" else "Anonymous"
        response['email'] = request.POST['email'] if request.POST['email'] != "" else "Anonymous"
        response['message'] = request.POST['message']
        message = Message(name=response['name'], email=response['email'],
                          message=response['message'])
        message.save()
        html ='aboutme/form_result.html'
        return render(request, html, response)
    else:        
        return HttpResponseRedirect('/aboutme/')

def message_table(request):
    message = Message.objects.all()
    response['message'] = message
    html = 'aboutme/table.html'
    return render(request, html,response)

aboutus/views.py
from django.shortcuts import render

# Create your views here.
# Create your views here.

response ={}
def index(request):    
    response['author'] = "Kezia Irene Tesiman"
    html = 'aboutus/aboutus.html'
    return render(request, html, response)

dashboard/views.py
from django.shortcuts import render

# Create your views here.

response ={}
def index(request):    
    response['author'] = "Kezia Irene Tesiman"
    html = 'dashboard/dashboard.html'
    return render(request, html, response)

post/views.py
from django.shortcuts import render

# Create your views here.

aboutme/templates/aboutme/aboutme.html
{% extends "YPM/layout/base.html" %}
{% load staticfiles%}

{% block style %}
    <!-- bootstrap csss -->
    <link href="https://fonts.googleapis.com/css?family=Dosis" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/aboutme.css' %}">
{% endblock %}

{% block content %}
<div class="profile">
<h1>Profile</h1>
</div>
<hr>

<section name="name">
    <p align = "center">
         <img src={{model_pic}} class="img-circle" widht="200" height="200">
    </p>

    <p align = "center">
        <div class = "name">
        <h2 align="center">{{name}}</h2>
        </div>
    </p>
</section>
<hr/>
<section name="about_me">
    <table class="table" align="center">
        <tr>
            <td>Birthday</td>
            <td>{{birthdate}}</td>
        </tr>
        <tr>
            <td>Gender</td>
            <td>{{gender}}</td>
        </tr>
        <tr>
            <td>Expertise</td>
            <td>
                {% for data in expertise %}
                    <span class="badge badge-pill badge-primary" id="bege">{{data.expertise}}</span>
                {% endfor %}
            </td>
        </tr>
        <tr>
            <td>Description</td>
            <td>{{description}}</td>
        </tr>
    </table>
</section>

<section name="form">
    <h2>Send Message</h2>
    <form id="form" method="POST" action="{% url 'aboutme:add_message' %}">
        {% csrf_token %}
        {{ message_form }}
        <br>
        <button type="submit" class="btn btn-default">Submit</button>
    </form>
</section>



{% endblock %}

aboutme/templates/aboutme/form_result.html
{% extends "YPM/layout/base.html" %}
{% block title %} Pesan dari {{ name }} {% endblock %}
{% block content %}
<h1 style="text-align:center;">Thank you for your message :)</h1>
<br> <h3 style="text-align:center;">Your message will not be visible for others</h3>
<br>
<textarea readonly rows="5" class="form-control">&quot;{{message}}&quot;-{{name}} 
    by {{ email }}
</textarea>
{% endblock %}

{% block footer %}
    <p> &copy; {{name}} </p>
{% endblock %}

aboutme/templates/aboutme/table.html
{% extends "YPM/layout/base.html" %}

{% block title %} Kumpulan Pesan {% endblock %}

{% block content %}
<!--  Populate semua isi pesan dari model -->
<table class="table">
    <thead>
        <th>Nama</th>
        <th>Email</th>
        <th>Pesan</th>
        <th>Dibuat Pada</th>
    </thead>
    <tbody>
        <!-- TODO, Kalau nama/email anon maka tr classnya jadi warning -->
        {% for i in message %}
        {% if i.name == 'Anonymous' or i.email == 'Anonymous' %}
        <tr class="warning"> {% else %} <tr class="success">
            {% endif %}
            <td> {{i.name}} </td>
            <td> {{i.email}} </td>
            <td> {{i.message}} </td>
            <td> {{i.created_date.time}} </td>
        </tr>             
        {% endfor %}
    </tbody>
</table>

{% endblock %}

dashboard/templates/dashboard/dashboard.html
{% extends "YPM/layout/base.html" %}


{% block style %}
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

{% endblock %}



{% block content %}

<style>
    .mySlides {display: none;}
</style>
<h1 class="w3-center">B. A. W. S. 2018 (Scroll ke bawah ya..)</h1>

<div class="w3-content w3-section" style="max-width:800px; max-height:100px">
  <img class="mySlides" src="https://docs.google.com/uc?id=1F3qbLU6ZwAJ7EWJ1yJ4zbvEgyE7uXeUI" style="width:100%">
  <img class="mySlides" src="https://docs.google.com/uc?id=1geCyfoo8Pp4ZJvBtDKAsVNFGQzUyInBg" style="width:100%">
  <img class="mySlides" src="https://docs.google.com/uc?id=1Rojz7ttziqBUWM7IQRxUZCqehLFpiUrO" style="width:100%">
  <img class="mySlides" src="https://docs.google.com/uc?id=1uwuvAtS586PILHMH97xJhLy14IJNodEw" style="width:100%">
  <img class="mySlides" src="https://docs.google.com/uc?id=1Y6aivs2v_1CkiHDJ-RupfYhWHfpFwROJ" style="width:100%">
</div>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
<div class= "paragraph">
    <p><h2 style="text-align: center;
        ">Surat Umum Buat Kalian Semua</h2></p>
    
    <pre>
        Hai guys.. Maaf bgt ya.. Mungkin surat dari gua yg terakhir sampe :")
    
        Jadi ya sekarang kira udah ada di penghujung tahun ajaran banget ya? Sebentar lagi ujian huaaa...
    

            Pertama, gua mau minta maaf dulu kepada kalian semua. Gua tau kok selama ini gua belum menjadi teman yang baik.
        Tapi percayalah kalau gua juga orang yang sedang berproses dan engga sempurna. Semoga kalian masih mau menerima gua
        sebagai teman kalian. Gua berjanji akan selalu berusaha buat menjadi pribadi yang lebih ramah, lebih mau mendengarkan, 
        lebih mau memahami, pokoknya yang lebih baik :"). Maaf buat kalian yang pernah sakit hati gara-gara perkataan maupun 
        perbuatan gua. Gua mungkin punya background yang kalian ga tau dan menyebabkan gua seperti ini. Plis jangan benci gua :"

            Kedua, website ini tolong jangan disebar ke siapa-siapa ya. Karena takutnya akan merusak reputasi gua di kalangan umum.
        Soalnya mungkin di website ini, gua akan cerita panjang lebar dan plis bgt jangan sampe di ekspos ke organisasi ataupun siapapun.
        Gua juga mengajak kalian kalo mau ngembangin website ini bareng-bareng, bilang gua aja ya.. Soalnya gua punya rencana kalau
        website ini nantinya juga jadi website angkatan kita (Setelah isinya dirombak obviously).

            Mungkin sejak PK 2 pertengahan kali ya, karakter gua yg sekarang mulai keluar. Entah kenapa gua juga bingung kenapa 
        karakter gua jadi begini. Dulu rasanya gua ga se ambis ini (ato iya?). Kadang gua mikir, seandainya gua bisa kembali ke masa lalu,
        apakah gua bisa berubah jadi orang yang lebih baik? Kenapa gua suka nge judge orang begitu rupa, kenapa gua egois banget, kenapa gua
        sombong banget, kenapa gua bossy banget. Kalau gua boleh minta tolong kalian buat bantu gua jadi orang yang lebih baik?

            Kenangan bareng kalian selama 3 tahun itu sangat berharga. Gua gaakan pernah lupa kalian, pejuang sejati yang memperjuangkan
        musik dan hal lainnya. Kalian orang-orang hebat yang pernah gua temui. Gua selalu ingat Mosyeh, teman gua yang pertama kali sejak 
        gua masuk YPM. Gua ga pernah lupa sama grup "Solfegio Horor", grup yang kita buat pas PK 1. Vanessa, Mira, Karin, Lidya, Mika, kalian
        orang yang pertama kali mau berteman sama gua (karena anak bintaro udah punya geng hehe). Gua ga akan bisa lupa sama Kezia Emanuella 
        dan Tata, kalian orang yang gua undang (dan dateng) ke sweet 17 gua. Yang selalu teringat Abi, Fipo, dan Aghai makasih ya udah mau nonton
        konser OSUI gua.. It means a world for me. Makasih udah mau dukung gua. Yang terlucu pas gua lagi gamelan: Fifi, Kenwin, Dhiya (pejuang 
        riong hehehe).Gua juga ga lupa sama grup "Baper kereta", grup para pejuang kereta, grup "Golden Solfe", grup para pelajar solfegio,
        grup "Baper Senin", yang mana gua di kick karena nyebarin jawaban (maaf :"), grup "Vanziswin Double Piano", grup duo piano yg gua banggakan
        (Mosyeh, Kenwin, Sasa), dan yang terkini grup "UI+YPM 2016", grup yang tadinya isinya cuma 3 orang yaitu gua, keze, dan fipo, lalu sekarang 
        isinya udah 9 ORANG!! Yang berisi teman-teman gua yang hebat bgt dan bisa bagi waktu kuliah sama YPM. Abi yang asisten lab, Aghai yang beneran
        merupakan panutan gua, Fipo yang selalu ceria, Odet yang ter hits, Keze yang tersibuk, Dhiya yang pejuang arsi (WOW), Graciel yang ambis, dan 
        tidak lupa Ben yang selalu menghibur. Terakhir juga ada grup "200 juta jingle", yang akhirnya demot :"). (Ada yang ke skip?)

            Sekali lagi gua mohon maaf ke kalian. Semua yang gua lakukan beneran gaada maksud buat melukai kalian kok. Terus kalau kalian ada saran 
        buat pengembangan diri gua, tolong bilang ke gua, karena kadang kalian lebih tau daripada gua sendiri. Oh iya, nanti ada surat buat kalian
        satu persatu di page <a href="{% url 'aboutus:index' %}"><b style="color:#FF000D;">about us</b></a>. Kalo bisa gua akan pakein password khusus buat kalian satu persatu. Plis jangan dimasukkin random, 
        ini web belom bener-bener banget. <u>Kezia masih cups</u>. Terus kalau kalian mau ninggalin pesan ke gua, bisa di post di halaman 
        <a href="{% url 'aboutme:index' %}"><b style="color:#FF0000;">about me</b></a>. Gua berharap banyak kalian mau ngasih saran buat gua apa aja :"). Kalian juga bisa kirim DUDU (Dari, Untuk, Dengan Ucapan)
        di page <b style="color:#FF0000;">Post</b>.


        Sekian dari gua, SEMANGAT UJIANNYA GAISS. Semoga kalian suka sama web gua.. 



        Salam, 


        Kezia Irene
        Ilmu Komputer 2016

    </pre>
</div>
{% block javascript%}
<script>
var myIndex = 0;
carousel();

function carousel() {
    var i;
    var x = document.getElementsByClassName("mySlides");
    for (i = 0; i < x.length; i++) {
       x[i].style.display = "none";  
    }
    myIndex++;
    if (myIndex > x.length) {myIndex = 1}    
    x[myIndex-1].style.display = "block";  
    setTimeout(carousel, 5000); // Change image every 2 seconds
}
</script>

{% endblock %}
{% endblock %}

templates/YPM/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="description" content="perusahaan lowongan">
   <meta name="author" content="{{author}}">
   <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
   <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Droid+Sans:400,700">
   {% block style %}
   {% endblock %}
   <title>
      {% block title %}
      {% endblock %}
   </title>
</head>
<body style="background-image: url(https://www.planwallpaper.com/static/images/518164-backgrounds.jpg)">
   <header>
        {% include "YPM/partials/header.html" %}
   </header>
   <content>
           {% block content %}
           {% endblock %}
   </content>
   <footer class = "footer">
       {% include "YPM/partials/footer.html" %}
   </footer>
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
   <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
   {% block javascript %}
   {% endblock %}
</body>
</html>

templates/YPM/partials/footer.html
{% load staticfiles %} {% load static %}
<div class="footer">
    <p>Made by &copy; Kezia Irene</p>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</script>

templates/YPM/partials/header.html
<!-- templates/partials/header.html -->
{% load staticfiles %} {% load static %}

<nav class="navbar navbar-default navbar-static-top">
      <div class="containers">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'dashboard:index' %}">Home</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <!-- LINK MENUJU table, dan link menuju home#form -->
            <li><a href="{% url 'aboutus:index' %}">About Us</a></li>
            <li><a href="{% url 'aboutme:index' %}">About Me</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
</nav>